name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Executa todo dia à meia-noite

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- Mantém seu passo atual para repo stats ---
      # Adicione aqui seu comando atual se tiver algo que gera repo-stats

      # --- Novo passo para gerar gráfico de linguagens ---
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3 python3-pip
          pip3 install matplotlib

      - name: Fetch GitHub repos languages and generate SVG
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Pega todos os repositórios públicos + privados
          curl -H "Authorization: token $GH_TOKEN" -s "https://api.github.com/user/repos?per_page=100" > repos.json

          # Inicializa JSON para somar linguagens
          echo '{}' > languages.json

          # Soma linguagens de todos os repositórios
          for repo in $(jq -r '.[].full_name' repos.json); do
            curl -H "Authorization: token $GH_TOKEN" -s "https://api.github.com/repos/$repo/languages" > lang.json
            jq -s '.[0] * .[1]' languages.json lang.json > tmp.json || cp lang.json tmp.json
            mv tmp.json languages.json
          done

          # Gera gráfico SVG via Python
          python3 - <<EOF
import json, matplotlib.pyplot as plt

with open("languages.json") as f:
    data = json.load(f)

# Ordena por mais usado e pega top 5
data = dict(sorted(data.items(), key=lambda x: x[1], reverse=True)[:5])

plt.figure(figsize=(5,2))
plt.bar(data.keys(), data.values(), color="#6272a4")
plt.title("Most Used Languages")
plt.tight_layout()
plt.savefig("lang-stats.svg", format="svg")
EOF

      - name: Commit and push updated SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add lang-stats.svg
          git commit -m "Update languages stats" || echo "No changes to commit"
          git push
